"""Add install_state to Installation model.

Revision ID: 0a468b6b9617
Revises: c5fa56b89e8e
Create Date: 2025-11-25 12:39:44.149425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a468b6b9617'
down_revision = 'c5fa56b89e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('install_state', sa.String(length=80), nullable=True))
        batch_op.create_unique_constraint('uq_installation_install_state', ['install_state'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installation', schema=None) as batch_op:
        batch_op.drop_constraint('uq_installation_install_state', type_='unique')
        batch_op.drop_column('install_state')

    # ### end Alembic commands ###
