"""Make user_id and access_token nullable in Installation model.

Revision ID: 8743e201ff0a
Revises: 0a468b6b9617
Create Date: 2025-11-25 13:09:53.723604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8743e201ff0a'
down_revision = '0a468b6b9617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installation', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installation', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
