"""Initial migration.

Revision ID: c5fa56b89e8e
Revises:
Create Date: 2025-11-25 12:36:06.430491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fa56b89e8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trmnl_id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trmnl_id')
    )
    op.create_table('installation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trmnl_installation_id', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=200), nullable=False),
    sa.Column('bus_stop', sa.String(length=100), nullable=True),
    sa.Column('bus_direction', sa.String(length=100), nullable=True),
    sa.Column('train_station', sa.String(length=100), nullable=True),
    sa.Column('train_destination', sa.String(length=100), nullable=True),
    sa.Column('min_train_time', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.String(length=100), nullable=True),
    sa.Column('app_key', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trmnl_installation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installation')
    op.drop_table('user')
    # ### end Alembic commands ###
